version: '3.8'
services:
  keycloak:
    # same version as in production Keycloak. See https://www.keycloak.org/server/containers
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: keycloak
    ports:
    - '9999:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
    - ./keycloak:/opt/keycloak/data/import
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev --import-realm" ]
